name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (no features)
      run: cargo build --verbose --no-default-features
    - name: Build (all features)
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: |
        cargo doc
        echo "<meta http-equiv=\"refresh\" content=\"0; url=energy_bus\">" > target/doc/index.html
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
